### ISSUE TITLE
openBaseline/closedBaseline

### ISSUE THREAD

**Issue by exus85** [konnectedvn/lovelace-vertical-slider-cover-card#14]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Home Assistant version:**

**Browser and Operating System:**

**Description of problem:**
Readme issue
openBaseline setting is not working, I think the right setting should be closedBaseline according to this line of code:

`var openBaseline = this.config.closedBaseline ? this.config.closedBaseline : 0;`
right?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by wolverinevn** [comment]
Thanks. Gonna fix it today.

**Comment by wolverinevn** [comment]
> **Checklist:**
> 
> * [x]  I updated to the latest version available
> * [x]  I cleared the cache of my browser
> 
> **Release with the issue:**
> 
> **Last working release (if known):**
> 
> **Home Assistant version:**
> 
> **Browser and Operating System:**
> 
> **Description of problem:**
> Readme issue
> openBaseline setting is not working, I think the right setting should be closedBaseline according to this line of code:
> 
> `var openBaseline = this.config.closedBaseline ? this.config.closedBaseline : 0;`
> right?
> 
> **Javascript errors shown in the web inspector (if applicable):**
> 
> ```
> 
> ```
> 
> **Additional information:**

Checked and my **closedBaseline** worked as intended. Could you please check your configuration for any spelling error?

**Comment by wolverinevn** [comment]
It's an error in sample code. Please change it.
Thanks!
