### ISSUE TITLE
Nothing shows - Custom card don't load

### ISSUE THREAD

**Issue by musicaways** [konnectedvn/lovelace-vertical-slider-cover-card#15]
**Checklist:**

- [V] I updated to the latest version available
- [V] I cleared the cache of my browser

**Release with the issue:** 
   0.1.2

**Home Assistant version:** 
   0.117.5

**Browser and Operating System:** 
   Chrome - Opera - raspberry buster with docker and homessistant

**Description of problem:**

Hi!!
i have e problem to load the custom card.
I checked the status of the shutters on developers tools and they are working.

Can you help me please?

There is Javascript error:

```javascript
`[konnected.vn] Vertical Slider Cover Card   Version v0.1.2
2vertical-slider-cover-card.js:172 Uncaught (in promise) TypeError: Cannot read property 'states' of undefined
    at vertical-slider-cover-card.js:172
    at Array.map (<anonymous>)
    at HTMLElement._stateCount (vertical-slider-cover-card.js:171)
    at HTMLElement.render (vertical-slider-cover-card.js:83)
    at HTMLElement.update (lit-element.js?module:160)
    at HTMLElement.performUpdate (updating-element.js?module:475)
    at HTMLElement._enqueueUpdate (updating-element.js?module:437)`
```
![Cattura](https://user-images.githubusercontent.com/18104463/98843408-38dbad00-244b-11eb-8884-ab5164127baa.JPG)

There is my code:

```javascript
action: call-service
service: browser_mod.popup
service_data:
  title: " "
  hide_header: true
  deviceID: this
  style: |
    :host .content {
      width: 50em;
    }
  card:
     type: custom:stack-in-card
     cards:
      - type: custom:vertical-slider-cover-card
        title: Tapparelle
        #background: 'rgba(0, 0, 0, 0.4)'
        #showButton: false
          #Call service instead of navigating -> comment 1 line above & uncomment all belows
          #buttonText: CLOSE
          #buttonService: cover.close_cover
          #buttonData: 'cover.office_left_blinds,cover.office_right_blinds,cover.basement_shutter'
        panelType: true
        showSidebar: false
        positionHeight: 300px
        positionWidth: 100px
        gapWidth: 50px
        #switchHeight: 80px
        #switchWidth: 100px
        showSwitch: false
        #openColor: 'hsl(0, 0%, 20%, 0.8)'
        #title: Covers
        #titleSize: 0px
        entities:
          - entity: cover.serranda_sala_piccola_roller_0
            name: Sala
```

**Comment by wolverinevn** [comment]
Please check your
          - entity: cover.serranda_sala_piccola_roller_0
            name: Sala
for spelling error.

**Comment by musicaways** [comment]
The entity name appear to be correct.
Other Possible Causes of the Error?

![Cattura](https://user-images.githubusercontent.com/18104463/98854200-8d3a5900-245a-11eb-9658-6a461a922ef7.JPG)

**Comment by musicaways** [comment]
Sorry for wasting your time @wolverinevn!
It was a custom: stack-in-card problem.

Thank you
