### ISSUE TITLE
Slider percentage set to NaN% and not working after HA restart

### ISSUE THREAD

**Issue by connysuxx** [konnectedvn/lovelace-vertical-slider-cover-card#16]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):*N/A*

**Home Assistant version :Home Assistant 0.118.4

**Browser and Operating System:*edge- W10* and also Safary on IOS mobile with HA app

**Description of problem:**
Sliders percentage set to NaN% and sliders not working after HA restart

**Javascript errors shown in the web inspector (if applicable):*N/A*

```

```

**Additional information:**
![Sliders stuck](https://user-images.githubusercontent.com/75178882/100622721-78e2d100-3321-11eb-8ad3-1053499f6ca4.PNG)

**Comment by wolverinevn** [comment]
Did you check if your cover would have had position attribute after Hass start? Your issue could be related to how Hass not preserve entity's state among restart.

**Comment by connysuxx** [comment]
Yes, you’ right, and I’m looking for a solution for this, the problem is if I don’t activate shutters first manually or using standard HA card, the sliders don’t work at all. You can imagine I would not have two cards on my Lovelace. By the way your sliders are perfect for my purpose, even the customizing options. Thank you for supporting.
