### ISSUE TITLE
Name and % are duplicated after latest release

### ISSUE THREAD

**Issue by mkjustuk** [konnectedvn/lovelace-vertical-slider-cover-card#25]
After updating to the latest release, the name and position % are duplicated above the sliders.

If I set showPosition: or showName: false or true, it's the same.

![image](https://user-images.githubusercontent.com/64651122/151769360-0c7e50f8-1e75-465b-9a95-610a4acaca2e.png)

**Comment by tiduspup** [comment]
Hello, 
i have the same issue.

<img width="863" alt="Screenshot 2022-02-01 at 04 21 16" src="https://user-images.githubusercontent.com/23476260/151908422-b2bb44a0-3e31-4661-b56c-2f6d1e7183d7.png">

**Comment by wolverinevn** [comment]
Fixed it.

**Comment by mkjustuk** [comment]
Showing perfectly again for me, thank you very much!

![image](https://user-images.githubusercontent.com/64651122/151927107-796d37c9-a6f8-4130-93c5-7d9a726b80b4.png)
