### ISSUE TITLE
Remove Left side title section or adjust size

### ISSUE THREAD

**Issue by tkhan456** [konnectedvn/lovelace-vertical-slider-cover-card#3]
**Is your feature request related to a problem? Please describe.**
Requested feature

**Describe the solution you'd like**
Be able to remove title section all together or adjust width.  Card ends up too wide due to title area to be able to use on phone interface.

**Describe alternatives you've considered**
Remove title area all together or move title area to top or bottom instead

**Additional context**

**Comment by wolverinevn** [comment]
Done. Please see new titleSize and showSidebar options.
Stack looks not good not mobile. I need more times, which I barely have, to work on it.
Thanks for your feedback! 🤠
