### ISSUE TITLE
adjust the text size in the side bar

### ISSUE THREAD

**Issue by Pirol62** [konnectedvn/lovelace-vertical-slider-cover-card#5]
a smaller size saves place on mobile phones

**Comment by Pirol62** [comment]
Hi, a picture in order to explain what I mean.
This is the maximum, which is available on a mobile display
![image](https://user-images.githubusercontent.com/48820003/87017449-46003b00-c1d0-11ea-9101-01ada251b2a5.png)
A smaller width of a bar makes no difference. It simply increases the free space on the right border.

**Comment by wolverinevn** [comment]
Done. Please see titleSize and showSidebar options.
Thanks for your feedback! 🤠

**Comment by Pirol62** [comment]
Well done, thank you
