### ISSUE TITLE
Doesn't work with Zemismart Curtains

### ISSUE THREAD

**Issue by peterspencer10** [konnectedvn/lovelace-vertical-slider-cover-card#9]
I can get the curtains to close with the button on the sidebar, but the slider won't work. When I try and see the cover's state it reports as unknown. Could this be the reason?

**Comment by wolverinevn** [comment]
Are you using your curtain with Tuya integration? Does it report current postion?
Without position information, card won't work.
I'm so sorry for late reply. Thanks for your feedback!

**Comment by peterspencer10** [comment]
It shows the position on the Smart Life app, but not on HA.

**Comment by wolverinevn** [comment]
> It shows the position on the Smart Life app, but not on HA.

So sorry, we can't support cover without position.

Should I close this?

**Comment by peterspencer10** [comment]
I guess so. What a shame. It's a very pretty card.
